### ISSUE TITLE
Order Email not received to 'admin' and 'customer'

### ISSUE THREAD

**Issue by saumilkothari80** [TycheSoftwares/custom-order-statuses-woocommerce-lite#25]
If Default order status is changed from "No changes" to any other status, then Admin and Customer don't receive a New order notification email from WooCommerce. https://www.screencast.com/t/lhrA9ikaST
Have changed default order status from 'no changes' to 'on hold' in screenshot and other fields unchanged.

**Comment by ashokrane** [comment]
@apeksha10 @kenil802 Why is this issue missed out by both of you? Many customers have pointed this out.

**Comment by apeksha10** [comment]
@vishalck as email section is available only on the Pro version. In Custom Order Status lite version we do not allow to send an email to the customer or Admin. 
https://www.screencast.com/t/WEIxDSL8vhq

**Comment by kenil802** [comment]
@ashokrane sir, in this there is some tip or Note we can say which is written in wp factory. I am sharing it:

Please note that if you are using plugin’s “Default order status” option, you may stop receiving some standard WooCommerce emails. This happens because triggers that send default WooCommerce emails are related to order status changes. For example “Processing order” email is sent on these order status changes: from failed to processing, from on-hold to processing, from pending to processing. And “Order on-hold” emails are sent on: from pending to on-hold, from failed to on-hold. So if you change the default order status, emails are never triggered. Possible workaround would be to create new email in plugin’s “Emails” section that would look like standard WooCommerce email.

**Comment by ashokrane** [comment]
@apeksha10 You read the issue description?

**Comment by ashokrane** [comment]
@kenil802 Yes, that is fine, but that is a bug. The last 6 reviews on https://wordpress.org/support/plugin/custom-order-statuses-woocommerce/reviews/ are screaming this issue.

**Comment by apeksha10** [comment]
Yes.. I read the issue description. here we talking about standard WooCommerce emails.

**Comment by kenil802** [comment]
@ashokrane  Ohh, I see sir, but I was not sure whether it is a bug or not. Because when I started handling the tickets, Komal and Upendra both informed me that this is the note which you have have to keep in mind when the customer says that the email is not working. So, I thought it is not a bug.

**Comment by ashokrane** [comment]
That's right @apeksha10. So there is no question of emails being available only in COS Pro version.

The point is that such an important issue was missed & earlier on one of the occasion when it was asked to be replicated by @dhruvins, the result of the test were told as the issue is not replicated.

**Comment by apeksha10** [comment]
Take a live copy, I am able to replicate the above issue.
when I change default order status then Admin and Customer don't receive a New order notification email from WooCommerce. 
If I couldn't change the default order status then standard WooCommerce emails are received fine.

**Comment by ashokrane** [comment]
@apeksha10 Please test with below cases & let me know:

1. Default Order status unchanged
2. Default order status changed to On hold
3. Default order status changed to Completed
4. Default order status changed to Processing
5. Default order status changed to <any custom status>

**Comment by apeksha10** [comment]
I checked below cases 
1. Default Order status unchanged ---- Email received to admin and customer
2. Default order status changed to On hold-- No email received to admin and customer
3. Default order status changed to Completed--No email received to admin and customer
4.  Default order status changed to Processing- No email received to admin and customer
5. Default order status changed to any custom status- No email received to admin and customer

**Comment by apeksha10** [comment]
1. If this is settings: https://www.screencast.com/t/8hopXox5 
If I place an order using Cash On Delivery then the only customer got the email. https://www.screencast.com/t/9GGISUjMgf

2. If this is settings: https://www.screencast.com/t/8hopXox5 
If I place an order using "Check Payment" or "Direct Bank Transfer" payment gateway then No email received.

**Comment by nitin-ts** [comment]
Hello,

I have added some code in file \ts\wp-content\plugins\custom-order-statuses-woocommerce\includes\class-alg-wc-custom-order-statuses-core.php file and I am attaching it too here.

@apeksha10, Please take that file and replace it to your localhost and test it again.

If it does not resolve issue then please met me know.

Thanks.

[class-alg-wc-custom-order-statuses-core.zip](https://github.com/TycheSoftwares/custom-order-statuses-woocommerce-lite/files/4999800/class-alg-wc-custom-order-statuses-core.zip)

**Comment by apeksha10** [comment]
@nitin-ts, after taking above file, all below cases working fine. 
Results
1. Default Order status unchanged ---- Email received to admin and customer
2. Default order status changed to On hold-- Email received to admin and customer
3. Default order status changed to Completed--Email received to admin and customer
4. Default order status changed to Processing-Email received to admin and customer
5. Default order status changed to any custom status-Email received to admin and customer
6. If this is settings: https://www.screencast.com/t/8hopXox5 If I place an order using Cash On Delivery : Email received to admin and customer
7. If this is settings: https://www.screencast.com/t/8hopXox5 
If I place an order using "Check Payment" or "Direct Bank Transfer" payment gateway: Email received to admin and customer

but I got one more issue while testing the above test case.
After placing an order, order received page shows some notice : https://www.screencast.com/t/ZiAMf5vTcS
