### ISSUE TITLE
Unable to edit or view the products on the backend of the Products page when the plugin is active.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-statuses-woocommerce-lite#26]
The client has faced an issue where he was unable to edit or view the products on the backend of the Products page. I was not able to replicate the issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18929

**Comment by apeksha10** [comment]
I wth latest git copy, I am not able to replicate the above issue.
Hence closed this issue and marked as a fixed label.
