### ISSUE TITLE
Bulk Action dropdown does not shows all status on woo-order page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-statuses-woocommerce-lite#29]
Bulk Action dropdown does not shows all status on woo-order page.

I have a total of 10 statuses in the Custom Order Tool section. https://www.screencast.com/t/7XVOH8aUT8w
"Add custom statuses to admin order bulk actions" setting enabled. https://www.screencast.com/t/xweDmluw8aE9

On edit order page, Bulk action dropdown does not show all status.
see the screenshot : https://www.screencast.com/t/z6shhoU2dLYG

**Comment by ashokrane** [comment]
@apeksha10 Why are you just going by the count of statuses?

The bulk action dropdown does show all the custom statuses. And except for custom statuses, WooCommerce only shows option to change status of orders to processing, on hold & completed statuses.
