### ISSUE TITLE
Order status is coming wrong if default order status is set as "No change" and Default BACS field set as any status.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-statuses-woocommerce-lite#33]
Order status is coming wrong if the default order status is set as No change and Default BACS field set as any status.

If the default order status is set as "No changes" and Default BACS field set as any custom status.
see the screenshot: https://www.screencast.com/t/7jAZ9xrvzqZ6

Now on the checkout page, I place an order using the BACS payment gateway then the woo order page shows "On hold" status which is wrong.
https://www.screencast.com/t/CJTsT5YPmpr
https://www.screencast.com/t/fS8MkCBBX64

Here, I tried with WC default status than to it is not working
https://www.screencast.com/t/kRMSBCVZV9y
https://www.screencast.com/t/eFyShaupJ

**Comment by apeksha10** [comment]
the above same issue replicates with Cash on the delivery payment gateway.
This is my set up: https://www.screencast.com/t/vjTdme1ojGk
After placing an order, the woo-order page shows Processing status.
see the screenshot: https://www.screencast.com/t/SzREMTuIs

It should display an "unfinished" status.

**Comment by ashokrane** [comment]
Issue #34 is same.

**Comment by apeksha10** [comment]
With the latest git copy. still, I am able to replicate the original issue.
this is my plugin settings: https://www.screencast.com/t/WQnxLjU2sp
On the checkout page, Place an order using BACS payment gateway then woo-order page shows On hold status
Result: https://www.screencast.com/t/ZVdQyeA31

But things are working fine for issue #34 
My settings: https://www.screencast.com/t/DHEQfaVN
Result: https://www.screencast.com/t/DHEQfaVN

Hence re-open this issue.
